Name: rustup
Version: 1.26.0
Release: 1%{?dist}
Summary: The Rust toolchain installer
License: MIT and ASL 2.0
URL: https://github.com/rust-lang/rustup.rs
Source0: https://github.com/rust-lang/rustup.rs/archive/%{version}.tar.gz#/%{name}-%{version}.tar.gz
Source1: rustup-profile.sh
BuildRequires: cargo
Requires: curl, xz, zstd
Provides: rust, cargo, rustfmt, rust-src, lib32-rust-libs, rust-musl, rust-wasm, rust-analyzer
Conflicts: rust, cargo, rustfmt

%global debug_package %{nil}

%description
The Rust toolchain installer.

%prep
%setup -q

%build
cargo build --release --features no-self-update --bin rustup-init

%install
install -d %{buildroot}/usr/lib/%{name}/bin
install -Dm755 target/release/rustup-init %{buildroot}/usr/bin/rustup

_binlinks=('cargo' 'rustc' 'rustdoc' 'rust-gdb' 'rust-lldb' 'rustfmt' 'cargo-fmt' 'cargo-clippy' 'clippy-driver' 'cargo-miri')

for link in "${_binlinks[@]}"; do
    ln -s /usr/bin/rustup "%{buildroot}/usr/bin/${link}"
done

ln -s /usr/bin/rustup "%{buildroot}/usr/lib/%{name}/bin/rust-analyzer"

install -Dm755 %{SOURCE1} %{buildroot}/etc/profile.d/%{name}.sh

mkdir -p %{buildroot}/usr/share/bash-completion/completions
%{buildroot}/usr/bin/rustup completions bash > %{buildroot}/usr/share/bash-completion/completions/rustup
%{buildroot}/usr/bin/rustup completions bash cargo > %{buildroot}/usr/share/bash-completion/completions/cargo

mkdir -p %{buildroot}/usr/share/fish/vendor_completions.d
%{buildroot}/usr/bin/rustup completions fish > %{buildroot}/usr/share/fish/vendor_completions.d/rustup.fish

mkdir -p %{buildroot}/usr/share/zsh/site-functions
%{buildroot}/usr/bin/rustup completions zsh > %{buildroot}/usr/share/zsh/site-functions/_rustup
%{buildroot}/usr/bin/rustup completions zsh cargo > %{buildroot}/usr/share/zsh/site-functions/_cargo

install -Dm644 LICENSE-MIT %{buildroot}/usr/share/licenses/%{name}/LICENSE-MIT
install -Dm644 LICENSE-APACHE %{buildroot}/usr/share/licenses/%{name}/LICENSE-APACHE

%files
%license /usr/share/licenses/%{name}/LICENSE-MIT
%license /usr/share/licenses/%{name}/LICENSE-APACHE
/usr/bin/rustup
/usr/bin/cargo
/usr/bin/rustc
/usr/bin/rustdoc
/usr/bin/rust-gdb
/usr/bin/rust-lldb
/usr/bin/rustfmt
/usr/bin/cargo-fmt
/usr/bin/cargo-clippy
/usr/bin/clippy-driver
/usr/bin/cargo-miri
/usr/lib/%{name}/bin
/etc/profile.d/%{name}.sh
/usr/share/bash-completion/completions
/usr/share/fish/vendor_completions.d
/usr/share/zsh/site-functions

%changelog
* Sun Jun 18 2023 ssfdust <ssfdust@gmail.com> - 1.26.0-1
- Initial spec file based on Arch Linux PKGBUILD, generated by gpt-4
